# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finish_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FinishWinow(object):
    def setupUi(self, FinishWinow):
        FinishWinow.setObjectName("FinishWinow")
        FinishWinow.resize(582, 515)
        self.label = QtWidgets.QLabel(FinishWinow)
        self.label.setGeometry(QtCore.QRect(140, 190, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(FinishWinow)
        QtCore.QMetaObject.connectSlotsByName(FinishWinow)

    def retranslateUi(self, FinishWinow):
        _translate = QtCore.QCoreApplication.translate
        FinishWinow.setWindowTitle(_translate("FinishWinow", "Dialog"))
        self.label.setText(_translate("FinishWinow", "You are logged in"))
